name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: TEST
      id: test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: TEST
        setup-command: ''
        command: javac LinkedStack.java && java LinkedStack
        input: |-
          1
          2
          3
          NULL
          2
          1
          4
          3
        expected-output: |-
          ENTER INTEGERS TO CREATE NODES (ENTER A NON-INTEGER TO EXIT):
          STACK USING LINKED LIST HAS BEEN CREATED
          3 -> 2 -> 1 -> null
          1.PUSH
          2.POP
          3.EXIT
          ENTER YOUR CHOICE:
          POPPED ELEMENT IS:3
          STACK ELEMENTS AFTER POP
          2 -> 1 -> null
          1.PUSH
          2.POP
          3.EXIT
          ENTER YOUR CHOICE:
          ENTER THE ELEMENT TO PUSH INTO STACK:
          STACK ELEMENTS AFTER PUSH OPERATION ARE:
          4 -> 2 -> 1 -> null
          1.PUSH
          2.POP
          3.EXIT
          ENTER YOUR CHOICE:
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
